server.port: 8085
spring:
  data:
    mongodb:
      uri: mongodb+srv://digisherpa:MongoSherpa21@digisherpa.h80qy.mongodb.net/digisherpa?retryWrites=true&w=majority
  rabbitmq:
    host: 49.50.107.94
    port: 5672
    virtual-host: teamteach
    username: admin
    password: DigiSherpa21

app:
  security:
    jwt:
      authtype: Bearer
      expirationmins: 1440
      uri: asd
      header: jjh
    authentication:
      type: DBBASED
    key:
      keytype: shared
      signingsecret: fe80::6184:62f1:2b9e:5b8313:8666:1qaz

exchange:
  signup: signupexchange

signup.routingkeys: event.createjournal
listen.queue.names: event.createjournal
