server.port: 8086
spring:
  data:
    mongodb:
      uri: mongodb+srv://teamteach:TeamTeach2021@cluster0.h80qy.mongodb.net/teamteach?retryWrites=true&w=majority

app:
  security:
    jwt:
      authtype: Bearer
      expirationmins: 1440
      uri: asd
      header: jjh
    authentication:
      type: DBBASED
    key:
      keytype: shared
      signingsecret: fe80::6184:62f1:2b9e:5b8313:8666:1qaz

