server.port: 8086
spring:
  data:
    mongodb:
      username: teamteach
      password: DigiSherpa2021
      database: teamteach
      port: 27017
      host: dev.myfamilycoach.ml
app:
  security:
    jwt:
      authtype: Bearer
      expirationmins: 1440
      uri: asd
      header: jjh
    authentication:
      type: DBBASED
    key:
      keytype: shared
      signingsecret: fe80::6184:62f1:2b9e:5b8313:8666:1qaz

